### ISSUE TITLE
Defining "close representations" of tachycardic

### ISSUE THREAD

**Issue by jcoop1219** [jcoop1219/bme547ci#2]
In the assignment description, you mentioned two examples of "close representations" of tachycardic being 1-2 missing letters or 1-2 misspelled letters.

For the purposes of this assignment, how should I handle 1-2 _added_ letters? Ex: tachyZcardic or tachycarddic

Should this be considered "close enough" to tachycardic and therefore return True?

**Comment by dward2** [comment]
Yes
