### ISSUE TITLE
Best etiquette for creating test scripts

### ISSUE THREAD

**Issue by jcoop1219** [jcoop1219/bme547ci#7]
I'm currently putting all of my test cases in one function with the parametrize decorator (see [test_tachycardia.py](https://github.com/jcoop1219/bme547ci/blob/master/test_tachycardia.py)).

Is this an acceptable way of going about creating these test cases? Or should I be making separate functions (or perhaps even separate modules) for different types of test cases? At the end of the day, all of these test cases are testing the same piece of functionality--the ability to do fuzzy string matching with up to 2 characters of tolerance.

**Comment by dward2** [comment]
That should be acceptable.  That is the whole point of the parametrize function.  If something needs to be run over and over again, use the shortcut.  The only reason to break it down into different test functions was if you wanted to categorize them.  So, you could have one test function that tests for capitalization.  Another for testing for spaces, etc.  But, the test code would be identical.  It would only maybe help with readability or organization if it was your preference.  

There is nothing wrong with how you have it now.
